package main.modelo;
// Generated 03-ene-2016 23:30:22 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AvatarImg generated by hbm2java
 */
@Entity
@Table(name = "avatar_img", catalog = "dark_sky")
public class AvatarImg implements java.io.Serializable {

	private String nombreAvatar;
	private String urlAvatar;

	public AvatarImg() {
	}

	public AvatarImg(String nombreAvatar) {
		this.nombreAvatar = nombreAvatar;
	}

	public AvatarImg(String nombreAvatar, String urlAvatar) {
		this.nombreAvatar = nombreAvatar;
		this.urlAvatar = urlAvatar;
	}

	@Id

	@Column(name = "NOMBRE_AVATAR", unique = true, nullable = false, length = 30)
	public String getNombreAvatar() {
		return this.nombreAvatar;
	}

	public void setNombreAvatar(String nombreAvatar) {
		this.nombreAvatar = nombreAvatar;
	}

	@Column(name = "URL_AVATAR", length = 100)
	public String getUrlAvatar() {
		return this.urlAvatar;
	}

	public void setUrlAvatar(String urlAvatar) {
		this.urlAvatar = urlAvatar;
	}

}
