package main.modelo;
// Generated 03-ene-2016 23:30:22 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NoticiasPortadaId generated by hbm2java
 */
@Embeddable
public class NoticiasPortadaId implements java.io.Serializable {

	private String imagenUrl;
	private String titulo;
	private String texto;

	public NoticiasPortadaId() {
	}

	public NoticiasPortadaId(String imagenUrl, String titulo, String texto) {
		this.imagenUrl = imagenUrl;
		this.titulo = titulo;
		this.texto = texto;
	}

	@Column(name = "IMAGEN_URL", length = 100)
	public String getImagenUrl() {
		return this.imagenUrl;
	}

	public void setImagenUrl(String imagenUrl) {
		this.imagenUrl = imagenUrl;
	}

	@Column(name = "TITULO", length = 100)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "TEXTO", length = 400)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NoticiasPortadaId))
			return false;
		NoticiasPortadaId castOther = (NoticiasPortadaId) other;

		return ((this.getImagenUrl() == castOther.getImagenUrl()) || (this.getImagenUrl() != null && castOther.getImagenUrl() != null && this.getImagenUrl().equals(castOther.getImagenUrl())))
			&& ((this.getTitulo() == castOther.getTitulo()) || (this.getTitulo() != null && castOther.getTitulo() != null && this.getTitulo().equals(castOther.getTitulo())))
			&& ((this.getTexto() == castOther.getTexto()) || (this.getTexto() != null && castOther.getTexto() != null && this.getTexto().equals(castOther.getTexto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getImagenUrl() == null ? 0 : this.getImagenUrl().hashCode());
		result = 37 * result + (getTitulo() == null ? 0 : this.getTitulo().hashCode());
		result = 37 * result + (getTexto() == null ? 0 : this.getTexto().hashCode());
		return result;
	}

}
