package main.modelo;
// Generated 03-ene-2016 23:30:22 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NoticiasPortada generated by hbm2java
 */
@Entity
@Table(name = "noticias_portada", catalog = "dark_sky")
public class NoticiasPortada implements java.io.Serializable {
	private static final long serialVersionUID = -5735106098152359350L;
	
	
	private NoticiasPortadaId id;

	public NoticiasPortada() {
	}

	public NoticiasPortada(NoticiasPortadaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "imagenUrl", column = @Column(name = "IMAGEN_URL", length = 100) ),
		@AttributeOverride(name = "titulo", column = @Column(name = "TITULO", length = 100) ), @AttributeOverride(name = "texto", column = @Column(name = "TEXTO", length = 400) ) })
	public NoticiasPortadaId getId() {
		return this.id;
	}

	public void setId(NoticiasPortadaId id) {
		this.id = id;
	}

}
