package main.modelo;
// Generated 03-ene-2016 23:30:22 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PostInfo generated by hbm2java
 */
@Entity
@Table(name = "post_info", catalog = "dark_sky")
public class PostInfo implements java.io.Serializable {

	private Integer id;
	private CuentasUsuario cuentasUsuario;
	private String titulo;
	private String texto;
	private String imagenUrl;
	private String etiqueta;
	private Date fechaCreacion;
	private Integer commentContador;
	private Set<PostComments> postCommentses = new HashSet<PostComments>(0);

	public PostInfo() {
	}

	public PostInfo(CuentasUsuario cuentasUsuario, String titulo, String texto, Date fechaCreacion) {
		this.cuentasUsuario = cuentasUsuario;
		this.titulo = titulo;
		this.texto = texto;
		this.fechaCreacion = fechaCreacion;
	}
	
	public PostInfo(CuentasUsuario cuentasUsuario, String titulo, String texto, String imagenUrl, String etiqueta) {
		this.cuentasUsuario = cuentasUsuario;
		this.titulo = titulo;
		this.texto = texto;
		this.imagenUrl = imagenUrl;
		this.etiqueta = etiqueta;
	}

	public PostInfo(CuentasUsuario cuentasUsuario, String titulo, String texto, String imagenUrl, String etiqueta, Date fechaCreacion, Integer commentContador, Set<PostComments> postCommentses) {
		this.cuentasUsuario = cuentasUsuario;
		this.titulo = titulo;
		this.texto = texto;
		this.imagenUrl = imagenUrl;
		this.etiqueta = etiqueta;
		this.fechaCreacion = fechaCreacion;
		this.commentContador = commentContador;
		this.postCommentses = postCommentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTOR", nullable = false)
	public CuentasUsuario getCuentasUsuario() {
		return this.cuentasUsuario;
	}

	public void setCuentasUsuario(CuentasUsuario cuentasUsuario) {
		this.cuentasUsuario = cuentasUsuario;
	}

	@Column(name = "TITULO", nullable = false, length = 50)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "TEXTO", nullable = false, length = 1000)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "IMAGEN_URL", length = 100)
	public String getImagenUrl() {
		return this.imagenUrl;
	}

	public void setImagenUrl(String imagenUrl) {
		this.imagenUrl = imagenUrl;
	}

	@Column(name = "ETIQUETA", length = 100)
	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_CREACION", nullable = true, length = 19)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "COMMENT_CONTADOR", precision = 9, scale = 0)
	public Integer getCommentContador() {
		return this.commentContador;
	}

	public void setCommentContador(Integer commentContador) {
		this.commentContador = commentContador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postInfo")
	public Set<PostComments> getPostCommentses() {
		return this.postCommentses;
	}

	public void setPostCommentses(Set<PostComments> postCommentses) {
		this.postCommentses = postCommentses;
	}

}
