package main.modelo;
// Generated 03-ene-2016 23:30:22 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PostContador generated by hbm2java
 */
@Entity
@Table(name = "post_contador", catalog = "dark_sky")
public class PostContador implements java.io.Serializable {

	private int contador;

	public PostContador() {
	}

	public PostContador(int contador) {
		this.contador = contador;
	}

	@Id

	@Column(name = "CONTADOR", nullable = false, precision = 9, scale = 0)
	public int getContador() {
		return this.contador;
	}

	public void setContador(int contador) {
		this.contador = contador;
	}

}
